### PR TITLE
Updated Lock Player

### PR DESCRIPTION
**Pull request by Addison118**
I need the theta permission

### CODE REVIEW

**Comment by PEMapModder** [comment]
Apparently you don't know what you are doing at all. There isn't even an `isPlayerAuthenticated` function in the main class, nor is there even a `$this->plugin` field in the `SessionEventListener` class. Do you even understand object-oriented programming in PHP?

**Comment by Addison118** [comment]
Why did you ask me to lock the player than if you haven't finished the main authentication process?

**Comment by Gamecrafter** [comment]
lmfao

**Comment by Addison118** [comment]
@GameCrafter That was a mess up on my part. For some reason I put an unused function there. Learned a lot since then though!

**Comment by Gamecrafter** [comment]
@Addison118 Lies.

**Comment by Addison118** [comment]
@Gamecrafter whats a lie? That I put an unused function there? No that is truth. I am always learning... Shouldn't everyone?

**Comment by Addison118** [comment]
@Gamecrafter Is there anything else you would like to point out to me? Victor?

**Comment by Addison118** [comment]
@Gamecrafter or should I say "point out"

**Comment by Gamecrafter** [comment]
@Addison118 Why did you submit "stolen content" to the PM forums?

**Comment by PEMapModder** [comment]
This is not a forum.

**Pull request closed without merging**
